In [1]:
import numpy as np

On utilise numpy pour des calculs numériques et il se base sur C

## Créer un tableau Numpy

In [2]:
data = np.array(
    [
        [1,5,9],
        [8,9,7]
    ]
)

In [3]:
data

array([[1, 5, 9],
       [8, 9, 7]])

_ndim_ nous permet de connaitre le nombre de dimensions d'un tableau

In [4]:
data.ndim

2

_shape_, quant à elle, nous permet d'avoir la forme

In [6]:
data.shape

(2, 3)

_size_ permet de connaitre le nombre d'éléments dedans

In [7]:
data.size

6

## Les attributs d'un tableau numpy

Voici un tableau d'un seul élément

In [8]:
data_un = np.array([
    1
])

Tableau d'une liste d'éléments

In [9]:
data_un = np.array([
    1, 5, 6
])

### Tableau d'une liste

In [10]:
data_un = np.array([
    [1,5,6]
])

In [11]:
data_un.ndim

2

### Tableau avec deux listes

In [12]:
data_deux = np.array([
    [1,5,6],
    [9,4,7]
])

In [13]:
data_deux.ndim

2

### Tableau avec trois listes

In [18]:
data = np.array([
    [1,5,6,2],
    [9,4,7,8],
    [0,1,0,6]
])

In [19]:
print(data[0][2])

6


### Tableau de trois dimensions

In [20]:
data_trois = np.array([
    [[1,5,9],
     [8,9,7]],
    
    [[2,5,9],
     [8,9,7]],

    [[13,5,9],
     [8,9,7]]
])

In [21]:
print(data_trois[0][0][2])

9


In [22]:
data_trois.shape

(3, 2, 3)

## Accéder aux éléments d'un tableau

In [23]:
data_trois[2,1,2]

np.int64(7)

Faire du slicing sur un sous_tableau

In [24]:
data_trois[0][1:]

array([[8, 9, 7]])

Ce slicing prend toutes les listes de 0 à la fin et à partir du deuxième éléments de chaque sous-liste

In [27]:
data_trois[0: , 1:]

array([[[8, 9, 7]],

       [[8, 9, 7]],

       [[8, 9, 7]]])

## Créer un tableau avec éléments aléatoires

_arange_ permet d'avoir un nombre d'éléments à la suive et _reshape_ permet de lui donner une forme

In [28]:
matrice = np.arange(9).reshape((3,3))

In [29]:
matrice

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Si le *=* nous permet de copier un tableau, il cré en fait une vue et ceci a l'erreur que toute modification sur la liste initiale entraîne une modification de la vue.

Le meilleur moyen d'éviter une telle situation est d'utiliser _.copy()_

In [30]:
data = matrice[:2, :2].copy()

In [31]:
data

array([[0, 1],
       [3, 4]])

## Créer un tableau de taille

La ligne de code ci-dessous crée un tableau de forme (2, 5) et le remplit avec des données aléatoires compris de 0 à 100

In [ ]:
x = np.random.randint(100, size=(2,5))

Avec reshape, on peut modifier la forme de l'élément, mais cette modification doit en faire sorte que le nombre d'éléments reste le même.

## Concaténer des tableaux numpy

In [32]:
u = np.array([
    [1,5,6]
])

In [33]:
v = np.array([
    [7,8,9]
])

Concaténer sur la vertical = vstack. Par contre l'horizontal est hstack et il concatène en ligne

In [34]:
tab = np.vstack([u,v])

In [35]:
tab

array([[1, 5, 6],
       [7, 8, 9]])

## Calcul sur les tableaux numpy

In [36]:
nombres = list(range(2, 9))

In [37]:
nombres

[2, 3, 4, 5, 6, 7, 8]

Nous utilisons la longueur de la liste nombres pour créer un tableau numpy vide (avec des données aléatoires) avec _.empty_

In [38]:
output = np.empty(len(nombres))
output

array([1.96337241e-316, 0.00000000e+000, 6.19495161e-310, 6.19495161e-310,
       6.19495161e-310, 6.19495161e-310, 3.47822215e-321])

enumerate permet de boucler et d'avoir et l'index et la valeur

In [39]:
for i, n in enumerate(nombres):
    output[i] = 1/n
output

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     ])

Plutot que de faire la boucle précédente qui est vorace en ressources, on peut profiter des avantages de numpy

In [41]:
tab_array = np.array(nombres)
1 / tab_array

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     ])

## La vectorisation

In [42]:
l = [5,8,9]
[n**2 for n in l]

[25, 64, 81]

In [43]:
np.array(l) ** 2

array([25, 64, 81])

In [44]:
np.array(l) + 1.5

array([ 6.5,  9.5, 10.5])

## Aggrégation

In [45]:
min(l)

5

In [46]:
np.min(l)

np.int64(5)

In [47]:
np.array(l).min()

np.int64(5)

In [49]:
np.random.seed(0)
tab = np.random.randint(15, size=(5, 3))
tab

array([[12,  5,  0],
       [ 3, 11,  3],
       [ 7,  9,  3],
       [ 5,  2,  4],
       [ 7,  6,  8]])

In [50]:
np.min(tab)

np.int64(0)

### Trouver le minimum sur un axe donné

In [51]:
np.min(tab, axis=0) #les colonnes

array([3, 2, 0])

In [52]:
np.min(tab, axis=1) #les lignes

array([0, 3, 3, 2, 6])

In [53]:
np.mean(tab, axis=1)

array([5.66666667, 5.66666667, 6.33333333, 3.66666667, 7.        ])

In [54]:
np.sum(tab, axis=0)

array([34, 33, 18])

## Analyse de données

On crée des données fictives

In [58]:
notes = np.random.randint(19, size=(10, 3))
notes

array([[ 0,  4,  5],
       [ 6,  8, 17],
       [15,  4,  9],
       [10,  1,  1],
       [ 7,  9,  3],
       [ 6, 11, 14],
       [18,  0, 14],
       [ 3, 12, 10],
       [11,  4,  6],
       [ 4, 15,  3]])

Chaque ligne représente un étudiant avec ses notes en Maths, Physique et Biologie

In [59]:
notes.shape

(10, 3)

La moyenne de chaque matière

In [61]:
notes.mean(axis=0)

array([8. , 6.8, 8.2])

Moyenne par étudiant

In [63]:
moy_etudiant = notes.mean(axis=1)
moy_etudiant

array([ 3.        , 10.33333333,  9.33333333,  4.        ,  6.33333333,
       10.33333333, 10.66666667,  8.33333333,  7.        ,  7.33333333])

Etudiants ayant une note >= 10

In [67]:
np.sum(moy_etudiant >= 10)

np.int64(3)